# -*- coding: utf-8 -*-
"""WEEK-15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUtRjF4Xz5gjDVAF6RlTtcVvuBuThkxj

**15. STUDENT EXAM PASS PREDICTION SYSTEM (LOGISTIC REGRESSION)**

**OBJECTIVE 1: DATA COLLECTION**

**CELL 1: MOUNT GOOGLE DRIVE**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**CELL 2: IMPORT REQUIRED LIBRARIES**"""

import pandas as pd
import numpy as np
# VISUALIZATION
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
# PREPROCESSING
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
# MODEL BUILDING
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# MODEL EVALUATION
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import warnings
warnings.filterwarnings('ignore')

"""**CELL 3: LOAD DATASET**"""

path = "/content/drive/MyDrive/Colab Notebooks/student_performance_dataset.csv"
df = pd.read_csv(path)
print("DATASET LOADED SUCCESSFULLY")

"""**CELL 4: DISPLAY DATASET**"""

df.head()

"""**CELL 5: DATASET INFORMATION**"""

df.info()

"""**CELL 6: DATASET SHAPE**"""

print("NUMBER OF ROWS :", df.shape[0])
print("NUMBER OF COLUMNS :", df.shape[1])

"""**OBJECTIVE 2: DATA CLEANING & PREPROCESSING**

**CELL 7: CHECK MISSING VALUES**
"""

df.isnull().sum()

"""**CELL 8: REMOVE DUPLICATES**"""

print("BEFORE REMOVING DUPLICATES :", df.shape)
df = df.drop_duplicates()
print("AFTER REMOVING DUPLICATES :", df.shape)

"""**CELL 9: CHECK DATA TYPES**"""

df.dtypes

"""**CELL 10: ENCODE CATEGORICAL VARIABLES**"""

le = LabelEncoder()
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
print("CATEGORICAL VARIABLES ENCODED SUCCESSFULLY")

"""**CELL 11: REMOVE STUDENT_ID**"""

if 'Student_ID' in df.columns:
    df.drop('Student_ID', axis=1, inplace=True)
print("STUDENT_ID COLUMN REMOVED")

"""**CELL 12: DISPLAY CLEANED DATASET**"""

df.head()

"""**OBJECTIVE 3: DESCRIPTIVE STATISTICS**

**CELL 13: STATISTICAL SUMMARY**
"""

df.describe()

"""**CELL 14: AVERAGE STUDY HOURS**"""

avg_study = df['Study_Hours_per_Week'].mean()
print("AVERAGE STUDY HOURS :", round(avg_study, 2))

"""**CELL 15: AVERAGE ATTENDANCE RATE**"""

avg_attendance = df['Attendance_Rate'].mean()
print("AVERAGE ATTENDANCE RATE :", round(avg_attendance, 2))

"""**CELL 16: AVERAGE PAST EXAM SCORES**"""

avg_past = df['Past_Exam_Scores'].mean()
print("AVERAGE PAST EXAM SCORE :", round(avg_past, 2))

"""**CELL 17: AVERAGE FINAL EXAM SCORE**"""

avg_final = df['Final_Exam_Score'].mean()
print("AVERAGE FINAL EXAM SCORE :", round(avg_final, 2))

"""**CELL 18: PASS VS FAIL COUNT**"""

df['Pass_Fail'].value_counts()

"""**OBJECTIVE 4: STUDENT PERFORMANCE ANALYSIS**

**CELL 19: PASS VS FAIL ANALYSIS**
"""

df.groupby('Pass_Fail').mean()

"""**CELL 20: INTERNET ACCESS IMPACT**"""

df.groupby('Internet_Access_at_Home')['Final_Exam_Score'].mean()

"""**CELL 21: EXTRACURRICULAR ACTIVITIES IMPACT**"""

df.groupby('Extracurricular_Activities')['Final_Exam_Score'].mean()

"""**OBJECTIVE 5: GROUP-BASED ANALYSIS**

**CELL 22: STUDY HOURS VS PASS/FAIL**
"""

study_analysis = df.groupby('Pass_Fail')['Study_Hours_per_Week'].mean()
study_analysis

"""**CELL 23: ATTENDANCE VS PASS/FAIL**"""

attendance_analysis = df.groupby('Pass_Fail')['Attendance_Rate'].mean()
attendance_analysis

"""**CELL 24: GENDER VS PASS RATE**"""

gender_analysis = df.groupby('Gender')['Pass_Fail'].mean()
gender_analysis

"""**CELL 25: PARENTAL EDUCATION ANALYSIS**"""

parent_analysis = df.groupby('Parental_Education_Level')['Final_Exam_Score'].mean()
parent_analysis

"""**OBJECTIVE 6: RELATIONSHIP ANALYSIS**

**CELL 26: CORRELATION MATRIX**
"""

corr = df.corr()
corr

"""**CELL 27: STUDY HOURS VS FINAL EXAM SCORE**"""

plt.figure(figsize=(8,5))
sns.scatterplot(
    x=df['Study_Hours_per_Week'],
    y=df['Final_Exam_Score'],
    color='maroon'
)
plt.title("STUDY HOURS VS FINAL EXAM SCORE")
plt.show()

"""**CELL 28: ATTENDANCE VS FINAL EXAM SCORE**"""

plt.figure(figsize=(8,5))
sns.scatterplot(
    x=df['Attendance_Rate'],
    y=df['Final_Exam_Score'],
    color='maroon'
)
plt.title("ATTENDANCE VS FINAL EXAM SCORE")
plt.show()

"""**OBJECTIVE 7: DATA VISUALIZATION**

**CELL 29: PASS VS FAIL DISTRIBUTION**
"""

fig = px.bar(
    df['Pass_Fail'].value_counts(),
    title='PASS VS FAIL DISTRIBUTION',
    color_discrete_sequence=['maroon']
)
fig.show()

"""**CELL 30: GENDER DISTRIBUTION**"""

fig = px.pie(
    df,
    names='Gender',
    title='GENDER DISTRIBUTION',
    color_discrete_sequence=['maroon']
)

fig.show()

"""**CELL 31: STUDY HOURS DISTRIBUTION**"""

fig = px.histogram(
    df,
    x='Study_Hours_per_Week',
    title='STUDY HOURS DISTRIBUTION',
    color_discrete_sequence=['maroon']
)

fig.show()

"""**CELL 32: ATTENDANCE RATE DISTRIBUTION**"""

fig = px.histogram(
    df,
    x='Attendance_Rate',
    title='ATTENDANCE RATE DISTRIBUTION',
    color_discrete_sequence=['maroon']
)
fig.show()

"""**CELL 33: FINAL EXAM SCORE DISTRIBUTION**"""

fig = px.histogram(
    df,
    x='Final_Exam_Score',
    title='FINAL EXAM SCORE DISTRIBUTION',
    color_discrete_sequence=['maroon']
)
fig.show()

"""**CELL 34: BOX PLOT FOR FINAL EXAM SCORE**"""

fig = px.box(
    df,
    y='Final_Exam_Score',
    title='BOX PLOT - FINAL EXAM SCORE',
    color_discrete_sequence=['maroon']
)
fig.show()

"""**CELL 35: CORRELATION HEATMAP**"""

fig = px.imshow(
    df.corr(),
    text_auto=True,
    title='CORRELATION HEATMAP',
    color_continuous_scale='Reds'
)

fig.show()

"""**OBJECTIVE 8: RISK ANALYSIS**

**CELL 36: CREATE RISK CATEGORIES**
"""

conditions = [
    (
        (df['Attendance_Rate'] < 60) &
        (df['Study_Hours_per_Week'] < 10) &
        (df['Past_Exam_Scores'] < 50)
    ),
    (
        (df['Attendance_Rate'] >= 60) &
        (df['Attendance_Rate'] < 80)
    ),
    (
        (df['Attendance_Rate'] >= 80)
    )
]
risk_labels = ['HIGH RISK', 'MEDIUM RISK', 'LOW RISK']
df['Risk_Level'] = np.select(conditions, risk_labels, default='NOT CLASSIFIED')
df[['Risk_Level']].head()

"""**CELL 37: RISK LEVEL DISTRIBUTION**"""

fig = px.pie(
    df,
    names='Risk_Level',
    title='RISK LEVEL DISTRIBUTION',
    color_discrete_sequence=['maroon']
)
fig.show()

"""**OBJECTIVE 9: PREDICTIVE MODELING (LOGISTIC REGRESSION)**

**CELL 38: DEFINE FEATURES AND TARGET**
"""

X = df.drop(['Pass_Fail', 'Risk_Level'], axis=1)
y = df['Pass_Fail']

"""**CELL 39: FEATURE SCALING**"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""**CELL 40: TRAIN TEST SPLIT**"""

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)
print("TRAINING DATA SHAPE :", X_train.shape)
print("TESTING DATA SHAPE :", X_test.shape)

"""**CELL 41: TRAIN LOGISTIC REGRESSION MODEL**"""

model = LogisticRegression()
model.fit(X_train, y_train)
print("MODEL TRAINING COMPLETED")

"""**CELL 42: PREDICTIONS**"""

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]
print(y_pred[:10])

"""**OBJECTIVE 10: MODEL EVALUATION**

**CELL 43: ACCURACY SCORE**
"""

accuracy = accuracy_score(y_test, y_pred)
print("ACCURACY :", round(accuracy*100,2), "%")

"""**CELL 44: PRECISION SCORE**"""

precision = precision_score(y_test, y_pred)
print("PRECISION :", round(precision,2))

"""**CELL 45: RECALL SCORE**"""

recall = recall_score(y_test, y_pred)
print("RECALL :", round(recall,2))

"""**CELL 46: F1 SCORE**"""

f1 = f1_score(y_test, y_pred)
print("F1 SCORE :", round(f1,2))

"""**CELL 47: CONFUSION MATRIX**"""

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Reds'
)
plt.title("CONFUSION MATRIX")
plt.xlabel("PREDICTED")
plt.ylabel("ACTUAL")
plt.show()

"""**CELL 48: CLASSIFICATION REPORT**"""

print(classification_report(y_test, y_pred))

"""**CELL 49: ROC-AUC SCORE**"""

roc_auc = roc_auc_score(y_test, y_prob)
print("ROC-AUC SCORE :", round(roc_auc,2))

"""**CELL 50: ROC CURVE**"""

fpr, tpr, threshold = roc_curve(y_test, y_prob)
plt.figure(figsize=(8,5))
plt.plot(fpr, tpr, color='maroon')
plt.plot([0,1], [0,1], color='maroon', linestyle='--')
plt.title("ROC CURVE")
plt.xlabel("FALSE POSITIVE RATE")
plt.ylabel("TRUE POSITIVE RATE")
plt.show()

"""**OBJECTIVE 11: DASHBOARD CREATION**

**CELL 51: STUDENT RISK DASHBOARD**
"""

fig = px.bar(
    df,
    x='Risk_Level',
    color='Pass_Fail',
    title='STUDENT RISK DASHBOARD',
    color_discrete_sequence=px.colors.sequential.Reds_r
)
fig.show()

"""**CELL 52: ATTENDANCE ANALYSIS DASHBOARD**"""

fig = px.scatter(
    df,
    x='Attendance_Rate',
    y='Final_Exam_Score',
    color='Pass_Fail',
    title='ATTENDANCE ANALYSIS DASHBOARD',
    color_discrete_sequence=px.colors.sequential.Reds_r
)

fig.show()

"""**CELL 53: STUDY HOURS DASHBOARD**"""

fig = px.scatter(
    df,
    x='Study_Hours_per_Week',
    y='Final_Exam_Score',
    color='Risk_Level',
    title='STUDY HOURS DASHBOARD',
    color_discrete_sequence=px.colors.sequential.Reds_r
)
fig.show()

"""**CELL 54: INTERACTIVE CORRELATION HEATMAP**"""

numeric_df = df.select_dtypes(include=np.number)
fig = px.imshow(
    numeric_df.corr(),
    text_auto=True,
    title='INTERACTIVE CORRELATION HEATMAP',
    color_continuous_scale='Reds_r'
)

fig.show()

"""**OBJECTIVE 12: INSIGHTS & CONCLUSION**

**CELL 55: FINAL INSIGHTS**
"""

print("""
1. STUDENTS WITH HIGHER ATTENDANCE PERFORM BETTER IN EXAMS.
2. STUDY HOURS POSITIVELY IMPACT FINAL EXAM SCORES.
3. PAST EXAM SCORES STRONGLY INFLUENCE PASS/FAIL PREDICTION.
4. INTERNET ACCESS IMPROVES STUDENT PERFORMANCE.
5. HIGH-RISK STUDENTS REQUIRE EARLY ACADEMIC SUPPORT.
6. LOGISTIC REGRESSION SUCCESSFULLY PREDICTS PASS/FAIL STATUS.
7. ATTENDANCE AND STUDY HABITS ARE MAJOR SUCCESS FACTORS.
8. VISUALIZATIONS AND DASHBOARDS SUPPORT DATA-DRIVEN DECISIONS.
""")